#spring相关配置
spring:

  #添加该配置后，解决Swagger异常
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #数据库配置
  datasource:
    dynamic:
      primary: primary

      #连接池配置
      druid:
        initialSize: 10
        minIdle: 1
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        filters: stat,log4j,wall
        useGlobalDataSourceStat: true

      #数据源配置
      datasource:

        #主数据源
        primary:
          url: jdbc:mysql://localhost:3306/common_test?characterEncoding=UTF-8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=true&rewriteBatchedStatements=true
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver

        #备数据源
        secondary:
          url: jdbc:mysql://localhost:3306/common_test?characterEncoding=UTF-8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=true&rewriteBatchedStatements=true
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver

#swagger配置
swagger:
  enabled: true
  title: '测试系统'
  description: "测试系统"
  version: '1.0'
  base-package: com.ftc.basecommon
